name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: npm install
      run: npm install
      
    - name: build project
      run: ./node_modules/.bin/nx run env:build --skip-nx-cache
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2  
      
    - name: Docker build
      uses: docker/setup-buildx-action@v2
      
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
    - name: Build and Push docker images
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/princesoni/app:latest
            ghcr.io/princesoni/app:1.0.0
    
      
        
