name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: npm install
      run: npm install
    - name: build project
      run: ./node_modules/.bin/nx run env:build --skip-nx-cache
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag env-prince-soni:latest1
    - name: push docker images
      run: docker push env-prince-soni:latest1
    
      
        
